Nav Bar
duan-le/HackTogether2020 pull request #5
Opened 2021-01-07 00:18 UTC by jshenny

Navigation bar and basic main page layout
![image](https://user-images.githubusercontent.com/34468739/103835292-162cd580-5043-11eb-8f7c-c6318083897b.png)
![image](https://user-images.githubusercontent.com/34468739/103835311-23e25b00-5043-11eb-9510-68dd04355b2a.png)

2021-01-18 01:38 UTC, JessieG123 requested changes

2021-01-18 01:38 UTC, JessieG123 commented on src/style.css
> +
Excess spacing

2021-01-18 01:38 UTC, JessieG123 commented on src/about/about.html
> +</footer>
Should have new line as best practice

2021-01-18 01:38 UTC, JessieG123 reviewed
Otherwise looks good to me!

2021-01-18 02:25 UTC, ahfhafh approved these changes

2021-01-24 00:10 UTC, JessieG123 approved these changes
Can merge

2021-02-05 20:28 UTC, closed without merging